version: '3.8'
services:
  web:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
